/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author priya
 */
public class CalcJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalcJFrame
     */
    public CalcJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResult = new javax.swing.JTextField();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnEqulas = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResult.setName(""); // NOI18N

        btnOne.setText("1");
        btnOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOneMouseClicked(evt);
            }
        });

        btnTwo.setText("2");
        btnTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTwoMouseClicked(evt);
            }
        });

        btnThree.setText("3");
        btnThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThreeMouseClicked(evt);
            }
        });

        btnFour.setText("4");
        btnFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFourMouseClicked(evt);
            }
        });

        btnFive.setText("5");
        btnFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiveMouseClicked(evt);
            }
        });

        btnSix.setText("6");
        btnSix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSixMouseClicked(evt);
            }
        });

        btnSeven.setText("7");
        btnSeven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSevenMouseClicked(evt);
            }
        });

        btnEight.setText("8");
        btnEight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEightMouseClicked(evt);
            }
        });

        btnNine.setText("9");
        btnNine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNineMouseClicked(evt);
            }
        });

        btnZero.setText("0");
        btnZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZeroMouseClicked(evt);
            }
        });

        btnReset.setText("CE");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        btnEqulas.setText("=");
        btnEqulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEqulasMouseClicked(evt);
            }
        });

        btnAdd.setText("+");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnSub.setText("-");
        btnSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubMouseClicked(evt);
            }
        });

        btnMultiply.setText("*");
        btnMultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplyMouseClicked(evt);
            }
        });

        btnDivide.setText("/");
        btnDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivideMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSeven, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btnOne, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnZero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(btnEight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFive, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEqulas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(btnNine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnSeven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEqulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOneMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnOne.getText());
            value1 = 1;          
        } else {
            txtResult.setText(txtResult.getText()+" " + btnOne.getText());
            value2 = 1;
        } 
    }//GEN-LAST:event_btnOneMouseClicked

    private void btnTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTwoMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnTwo.getText());
            value1 = 2;          
        } else {
            txtResult.setText(txtResult.getText()+" " + btnTwo.getText());
            value2 = 2;
        } 
    }//GEN-LAST:event_btnTwoMouseClicked

    private void btnThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThreeMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnThree.getText());
            value1 = 3;          
        } else {
            txtResult.setText(txtResult.getText()+ " " + btnThree.getText());
            value2 = 3;
        } 
    }//GEN-LAST:event_btnThreeMouseClicked

    private void btnFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFourMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnFour.getText());
            value1 = 4;          
        } else {
            txtResult.setText(txtResult.getText()+ " " + btnFour.getText());
            value2 = 4;
        } 
    }//GEN-LAST:event_btnFourMouseClicked

    private void btnFiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiveMouseClicked
        // TODO add your handling code here:
        
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnFive.getText());
            value1 = 5;          
        } else {
            txtResult.setText(txtResult.getText()+ " " + btnFive.getText());
            value2 = 5;
        } 
           
    }//GEN-LAST:event_btnFiveMouseClicked

    private void btnSixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSixMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnSix.getText());
            value1 = 6;          
        } else {
            txtResult.setText(txtResult.getText()+ " " + btnSix.getText());
            value2 = 6;
        }
    }//GEN-LAST:event_btnSixMouseClicked

    private void btnSevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSevenMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnSeven.getText());
            value1 = 7;          
        } else {
            txtResult.setText(txtResult.getText()+ " " + btnSeven.getText());
            value2 = 7;
        }
    }//GEN-LAST:event_btnSevenMouseClicked

    private void btnEightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEightMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnEight.getText());
            value1 = 8;          
        } else {
            txtResult.setText(txtResult.getText()+ " " + btnEight.getText());
            value2 = 8;
        }
    }//GEN-LAST:event_btnEightMouseClicked

    private void btnNineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNineMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnNine.getText());
            value1 = 9;          
        } else {
            txtResult.setText(txtResult.getText()+ " " + btnNine.getText());
            value2 = 9;
        }
    }//GEN-LAST:event_btnNineMouseClicked

    private void btnZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZeroMouseClicked
        // TODO add your handling code here:
         if(txtResult.getText().isEmpty())
        {
            txtResult.setText(btnZero.getText());
            value1 = 0;          
        } else {
            txtResult.setText(txtResult.getText()+ " " + btnZero.getText());
            value2 = 0;
        }
    }//GEN-LAST:event_btnZeroMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        txtResult.setText("");
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        if(!(txtResult.getText().isEmpty())){
        operator = "plus";
        txtResult.setText(txtResult.getText()+ " + ");
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubMouseClicked
        // TODO add your handling code here:
        if(!(txtResult.getText().isEmpty())){
        operator = "minus";
        txtResult.setText(txtResult.getText()+ " - ");
        }
    }//GEN-LAST:event_btnSubMouseClicked

    private void btnMultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplyMouseClicked
        // TODO add your handling code here:
        if(!(txtResult.getText().isEmpty())){
        operator = "multiply";
        txtResult.setText(txtResult.getText()+ " * ");
        }
    }//GEN-LAST:event_btnMultiplyMouseClicked

    private void btnDivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMouseClicked
        // TODO add your handling code here:
        if(!(txtResult.getText().isEmpty())){
        operator = "divide";
        txtResult.setText(txtResult.getText()+ " / ");
        }
    }//GEN-LAST:event_btnDivideMouseClicked

    private void btnEqulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqulasMouseClicked
        // TODO add your handling code here:
        double answer = 0;
         if(operator == "plus"){
             answer = value1 + value2;}
         else if(operator=="minus"){
             answer = value1 - value2;}
         else if (operator == "multiply"){
             answer = value1 * value2;}
         else if(operator == "divide"){
             answer = value1/value2;}
        
         String Result = Double.toString(answer);
         txtResult.setText(Result);
    }//GEN-LAST:event_btnEqulasMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        int firstnum;
    int secondnum;
    int result;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcJFrame().setVisible(true);
            }
        });
    }
    static int value1;
    static int value2;
    static String operator;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqulas;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
